### ISSUE TITLE
报错Unable to start web server

### ISSUE THREAD

**Issue by lowlowhight** [anyshift/flip#2]
java使用17版本，mysql8.0，启动项目就会报错，有知道是什么原因的大佬吗

**Comment by anyshift** [comment]
感谢反馈，上次调整结构后还有地方没修改过来，导致目录识别错误，因此导致此问题。

可能后续还有小问题，欢迎继续反馈：）

Tip：启动后，存放静态文件的文件夹需要本地自行创建，不然 Logo 和用户头像这些数据都加载不出来。
