### ISSUE TITLE
项目部署后，截图中的功能没有全部实现

### ISSUE THREAD

**Issue by Hansen747** [anyshift/flip#4]
我按照步骤启动项目后，解决完环境等问题，目前在本地上未能全部实现截图中的可用功能，且前后端均无报错，请问该项目目前开发完整了吗

**Comment by anyshift** [comment]
> 未能全部实现截图中的可用功能

举个例子？

---

该项目目前并未开发完整，已经一度停止开发了，后面时间充裕后会考虑推倒重来。如果你技术尚可的话，不妨试着对本项目进行大修小修：）

**Comment by Hansen747** [comment]
> > 未能全部实现截图中的可用功能
> 
> 举个例子？
> 
> 该项目目前并未开发完整，已经一度停止开发了，后面时间充裕后会考虑推倒重来。如果你技术尚可的话，不妨试着对本项目进行大修小修：）

不好意思，是我的问题，我给改坏了。
